language: csharp
solution: PersistentScienceCollectorAI.sln
env:
  global:
  - KSP_VERSION="1.5.1"

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq p7zip-full bash openssh-client jq

script:
- mkdir -p ../../KSP_x64_Data/Managed/
- wget https://img.spaceball.cf/KSP-$KSP_VERSION.7z
- 7za x KSP-$KSP_VERSION.7z -o../../KSP_x64_Data/Managed/ -p$ZIP_PASSWORD
- msbuild /p:Configuration=Release /p:BuildProjectReferences=false PersistentScienceCollectorAI.sln
- ls -lisa Plugin/
