#!/bin/sh

. ./.travis/semver.sh

TRAVIS_MAJOR=0
TRAVIS_MINOR=0
TRAVIS_PATCH=0
TRAVIS_FEATURE=0

semverParseInto "$TRAVIS_BRANCH" TRAVIS_MAJOR TRAVIS_MINOR TRAVIS_PATCH TRAVIS_FEATURE

TRAVIS_RELEASE_VERSION="$TRAVIS_MAJOR.$TRAVIS_MINOR.$TRAVIS_PATCH$TRAVIS_FEATURE"